Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'GradinaruFelix.Pipedrive:PersonFinisher':
            implementationClassName: GradinaruFelix\Pipedrive\Finishers\PersonFinisher
            options: {  }
