Gmedia:
  PipedriveFinisher:
    Api:
      Domain: ''
      Token: ''
    Form:
      Finisher:
        Activity:
          defaultValue: 'call'
Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'Gmedia.PipedriveFinisher:ActivityFinisher':
            implementationClassName: Gmedia\PipedriveFinisher\Finishers\ActivityFinisher
            options: {  }
          'Gmedia.PipedriveFinisher:DealFinisher':
            implementationClassName: Gmedia\PipedriveFinisher\Finishers\DealFinisher
            options: {  }
          'Gmedia.PipedriveFinisher:NoteFinisher':
            implementationClassName: Gmedia\PipedriveFinisher\Finishers\NoteFinisher
            options: {  }
          'Gmedia.PipedriveFinisher:OrganizationFinisher':
            implementationClassName: Gmedia\PipedriveFinisher\Finishers\OrganizationFinisher
            options: {  }
          'Gmedia.PipedriveFinisher:PersonFinisher':
            implementationClassName: Gmedia\PipedriveFinisher\Finishers\PersonFinisher
            options: {  }
